### ISSUE TITLE
Fix Better Kirka Client for Linux x86_64

### ISSUE THREAD

**Issue by rusluck** [42infi/better-kirka-client#10]
Everytime I run, I get this error message
```
(node:4145) UnhandledPromiseRejectionWarning: Error: Image could not be created from /tmp/.mount_betterMa0HkA/resources/app.asar/src\icon.png
    at createWindow (/tmp/.mount_betterMa0HkA/resources/app.asar/src/index.js:124:15)
    at /tmp/.mount_betterMa0HkA/resources/app.asar/src/index.js:294:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:4145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Something about electron, so go fix it or send me source code

**Comment by 42infi** [comment]
So dont use linux or get the code yourself but whatever I updated the linux builds in the latest release they might work now
